# PROJECT_ROOT/docker-compose.yml

version: '3.8'

services:
  #######################
  # Node.js App Service #
  #######################
  node_app:
    build:
      context: ./node_app # Node.js 앱 파일들이 있는 디렉토리
      dockerfile: Dockerfile # ./node_app/Dockerfile 을 사용
    ports:
      - "45315:3103" # 호스트 포트:컨테이너 포트 (Node.js 앱이 3103번 포트 사용)
    volumes:
      - ./node_app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped